### ISSUE TITLE
Squeak 6.0 alpha file name encoding error under Windows 10 Chinese Edition

### ISSUE THREAD

**Issue by dram** [squeak-smalltalk/squeak-object-memory#10]
In Squeak 6.0 alpha, `SimplifiedChineseEnvironment fileNameConverterClass` is `CNGBTextConverter`, which is incorrect under Windows 10 Chinese Edition.

After adding an overloaded method `SimplifiedChineseEnvironment class>>fileNameConverterClass` which returns `UTF8TextConverter`, and then do a reset with `LanguageEnvironment resetKnownEnvironments`, unicode file names show correctly in FileList tool.

**Comment by dram** [comment]
Submit a patch to The Inbox: https://lists.squeakfoundation.org/pipermail/squeak-dev/2022-May/220227.html

**Comment by marceltaeumel** [comment]
Merged.
