### ISSUE TITLE
Squeak 6.0 alpha incorrect input interpreter under Windows 10 Chinese Edition

### ISSUE THREAD

**Issue by dram** [squeak-smalltalk/squeak-object-memory#11]
In Squeak 6.0 alpha, `SimplifiedChineseEnvironment inputInterpreterClass` is `WinGB2312InputInterpreter`, which is incorrect under Windows 10 Chinese Edition.

After changing to `UTF32CNInputInterpreter` for `Win32` in `SimplifiedChineseEnvironment class>>inputInterpreterClass` and running following cleanups, chinese input works properly.

```
HandMorph clearInterpreters.
LanguageEnvironment resetKnownEnvironments.
```

**Comment by dram** [comment]
Submit a patch to The Inbox: https://lists.squeakfoundation.org/pipermail/squeak-dev/2022-May/220227.html

**Comment by marceltaeumel** [comment]
Merged.
