### ISSUE TITLE
Squeak 6.0 alpha "Set Etoys Mode" failed with "MNU: False>>owner"

### ISSUE THREAD

**Issue by dram** [squeak-smalltalk/squeak-object-memory#12]
When trying to enable "Extras > Themes & Colors > Set Etoys Mode" from menu bar, Squeak failed with following error:

![image](https://user-images.githubusercontent.com/517130/166105443-24011307-2324-4032-b967-3adb77423352.png)

Squeak version: Squeak6.0alpha-21659-64bit-202204190959-Windows-x64

**Comment by dram** [comment]
The problem is caused by "Morphic-ct.1905": http://lists.squeakfoundation.org/pipermail/squeak-dev/2022-February/219248.html

In that patch, return value of `Morph>>setProperty:toValue:` is changed, which will cause return value of `SuguarNavigatorBar>>inARow:` to be `false`.

**Comment by dram** [comment]
Submit a patch to The Inbox https://lists.squeakfoundation.org/pipermail/squeak-dev/2022-May/220232.html

**Comment by marceltaeumel** [comment]
Merged. Thanks!
