### ISSUE TITLE
Bug: Themes not properly updating in minimized windows

### ISSUE THREAD

**Issue by Phantonia** [squeak-smalltalk/squeak-object-memory#121]
When a window like a workspace or a browser is minimized and the Squeak theme is updated, this change is not reflected in these windows

**Comment by marceltaeumel** [comment]
Would you copy the data from the dialog window "Squeak > Feedback..."? You can copy-paste the text there.

![grafik](https://github.com/squeak-smalltalk/squeak-object-memory/assets/5765308/9c7c4760-41d5-435f-8763-d211a4ddafaa)

**Comment by LinqLover** [comment]
Thanks for the bug report @Phantonia!

I think I already fixed that one for Squeak Trunk: 

- https://lists.squeakfoundation.org/archives/list/squeak-dev@lists.squeakfoundation.org/thread/RNK3IM45WLMN5QVY3J3FFUEMPZYZNMS5/
- https://lists.squeakfoundation.org/archives/list/squeak-dev@lists.squeakfoundation.org/thread/WTMELPRAQRARVMWUMHGZJFJIZAIAQFKL/

You could try to apply this patch manually to your image and test if the issue does not occur any longer.

@marceltaeumel Shall we backport this patch to Squeak 6.0?

**Comment by Phantonia** [comment]
In case this is still necessary, here is the information from my Squeak image:
```
	OS: Win32 10.0 X64
	VM: 202312181441 (cc2dd90)
	SQ: Squeak6.0 #22148 (64 bit)
```

**Comment by marceltaeumel** [comment]
Fixed via `Morphic-mt.2034`. Just click "Squeak > Update Squeak" :-)
