### ISSUE TITLE
MVCUIManager>>#confirm: does not automatically wrap long text -- but Morphic does

### ISSUE THREAD

**Issue by tcj** [squeak-smalltalk/squeak-object-memory#13]
As usual, a `#confirm:` with embedded newlines:

```
self confirm: 'We respect your privacy. To minimize your receipt 
of duplicate information and for internal recordkeeping purposes, 
Squeak may track responses, if any, to this offer. Read more about 
Squeak''s privacy policy.'
```

in MVC, becomes:

![Screen Shot 2022-04-30 at 8 39 38 AM](https://user-images.githubusercontent.com/2293335/166112369-e2b65725-bf60-4db8-9844-ade7ce7e4cda.png)

while without the embedded newlines:

```
self confirm: 'We respect your privacy. To minimize your receipt of duplicate information and for internal recordkeeping purposes, Squeak may track responses, if any, to this offer. Read more about Squeak''s privacy policy.'
```

becomes in MVC:

![Screen Shot 2022-04-30 at 8 38 26 AM](https://user-images.githubusercontent.com/2293335/166112336-048e143a-9f21-4f9c-aa4f-5e16b8c6df88.png)

This is probably very standard behavior... but note that it becomes a problem w/r/t the (very cool btw :) ) welcome text in `Utilities class>>#setAuthorInitials` — which in MVC looks like this:

![Screen Shot 2022-04-30 at 8 42 09 AM](https://user-images.githubusercontent.com/2293335/166112483-2c3f2a13-65c0-4974-ba60-12812b6575d3.png)

Compare this to Morphic's implementation:  Somewhere in `DialogWindow` / `UserDialogBoxMorph`, the text gets wrapped:

![Screen Shot 2022-04-30 at 8 49 54 AM](https://user-images.githubusercontent.com/2293335/166112735-22e70b31-f342-479a-9ed6-0ca0eb5de338.png)

_(Note that the example text I used here was just lazily stolen from a bulk email, and is not something that would actually appear in Squeak.)_

**Comment by LinqLover** [comment]
I'm pretty sure that I have fixed this a few weeks ago, are you using the latest Trunk?

**Comment by tcj** [comment]
@LinqLover indeeds, this is in 21674, which I just downloaded today.  21674 seems to be from 2022-04-28

**Comment by LinqLover** [comment]
Sorry for the confusion! There is an unmerged patch for this at the moment, I hope I will be able to improve and merge it soon: https://lists.squeakfoundation.org/pipermail/squeak-dev/2022-April/219789.html
![mvcLineLengthDialogs](https://user-images.githubusercontent.com/38782922/166126200-ab944dad-eeb7-46f6-8871-76ff3d2ffdf9.png)

**Comment by marceltaeumel** [comment]
Merged:
- ST80-mt.284
- ToolBuilder-MVC-mt.68
- Morphic-mt.1979
