### ISSUE TITLE
Inconsistent encoding between reading and writing .st files in FileList

### ISSUE THREAD

**Issue by dram** [squeak-smalltalk/squeak-object-memory#15]
In Squeak 6.0 alpha, when I trying to edit .st file which contain Unicode characters, contents of this file will be disrupted after save.

According to changes of Tools-mt.1117 (http://lists.squeakfoundation.org/pipermail/squeak-dev/2022-January/218717.html), `FileList>>setDefaultEncoderFor:` will using `UTF8TextConverter` to reading .st and .cs files, but it seems that it has no effect when do writing.

**Comment by dram** [comment]
Submit a patch to The Inbox https://lists.squeakfoundation.org/pipermail/squeak-dev/2022-May/220229.html

**Comment by marceltaeumel** [comment]
Merged.
