### ISSUE TITLE
Incorrect WebServer document

### ISSUE THREAD

**Issue by dram** [squeak-smalltalk/squeak-object-memory#24]
In "Error Handling" section of WebServer document, arguments of block passed to `errorHandler:` seems incorrect, which is inconsistent with document in `WebServer>>#errorHandler:` code.

And `WebServer>>#handleError:socket:` does not exists, which may be `WebServer>>#handleError:request:`.

**Comment by codeZeilen** [comment]
@marceltaeumel Fixed in WebClient-Help-pre.14
