### ISSUE TITLE
`MIMEDocument class>>#guessTypeFromName:` failed for png images

### ISSUE THREAD

**Issue by dram** [squeak-smalltalk/squeak-object-memory#26]
In Squeak 6.0, `MIMEDocument class>>#guessTypeFromName:` failed to guess MIME type for png image files, i.e.:

```
MIMEDocument guessTypeFromName: 'foo.png' => 'application/octet-stream' 
```

Which should be `image/png`.

**Comment by dram** [comment]
Seems that MIME database is not consistent between code and image, after reset, it works:

```
MIMEDocument resetMIMEdatabase.
MIMEDocument guessTypeFromName: 'foo.png' => 'image/png'
```

**Comment by marceltaeumel** [comment]
Fixed via Network-mt.261.

**Comment by dram** [comment]
Fix confirmed, thanks!
