### ISSUE TITLE
Copy JSON ancestry to Trunk

### ISSUE THREAD

**Issue by LinqLover** [squeak-smalltalk/squeak-object-memory#43]
@tonyg kindly already copied the latest JSON version to the Trunk repository (JSON-ul.56). Next we should discuss whether we can copy over the entire ancestry as well, or whether there are unexpected problems with this. It would be helpful to have all ancestry available in source.squeak.org.

**Comment by tonyg** [comment]
No problems on my side! There should be no licencing problems either as contributions to the squeaksource repo are implicitly MIT.

**Comment by LinqLover** [comment]
Done, so all the tools like browse revisions are now available for the JSON package, too. :-)

![image](https://user-images.githubusercontent.com/38782922/189156209-61164b2e-0ac7-4364-a12a-b331836f52f4.png)

One more note: There are several contributors to this package that are not listed in the "About" page (aesp, dkb, klub, ...). Is there anything we should do with that?

**Comment by j4yk** [comment]
Depending on the license statement of the JSON package, we may be obliged to add their names to the distribution. Apart from it being a nice thing to do. Although GDPR sometimes has me wonder whether attributions are still as permitted as they are required by some licenses, haha.

Half off-topic:
Adding the ancestry versions caused some noise on the mailing list. It did not bother me, but some were bothered by that recent incident where old versions were posted again to the list. Would it be worthwhile to let Squeaksource filter out ancestors of versions that were already in the repository before sending these mails?

**Comment by LinqLover** [comment]
> Depending on the license statement of the JSON package, we may be obliged to add their names to the distribution. Apart from it being a nice thing to do. Although GDPR sometimes has me wonder whether attributions are still as permitted as they are required by some licenses, haha.

Complicated topic. Need to escalate to the board? One might argue that the author initials/author field in each MCVersionInfo already constitutes an attribution. Would it make sense in mentioning all unmatched initials in the contributors list as well? Some of them even contain a full name. Should we write a general reminder to squeak-dev?

---

> Adding the ancestry versions caused some noise on the mailing list. It did not bother me, but some were bothered by that recent incident where old versions were posted again to the list. Would it be worthwhile to let Squeaksource filter out ancestors of versions that were already in the repository before sending these mails?

I don't think so, such a heuristic would rather create confusion IMHO. For instance, SIT is currently limited to displaying inbox/trunk versions that were announced on the list ... (By the way, this "noise" could actually have documented all the diffs of the JSON package on the list, but unfortunately, I uploaded the versions in the reverse order. :D)


________________________________
Von: Jakob Reschke ***@***.***>
Gesendet: Sonntag, 11. September 2022 17:50 Uhr
An: squeak-smalltalk/squeak-object-memory ***@***.***>
Cc: Christoph Thiede ***@***.***>; State change ***@***.***>
Betreff: Re: [squeak-smalltalk/squeak-object-memory] Copy JSON ancestry to Trunk (Issue #43)


Depending on the license statement of the JSON package, we may be obliged to add their names to the distribution. Apart from it being a nice thing to do. Although GDPR sometimes has me wonder whether attributions are still as permitted as they are required by some licenses, haha.

Half off-topic:
Adding the ancestry versions caused some noise on the mailing list. It did not bother me, but some were bothered by that recent incident where old versions were posted again to the list. Would it be worthwhile to let Squeaksource filter out ancestors of versions that were already in the repository before sending these mails?

**Comment by j4yk** [comment]
> (By the way, this "noise" could actually have documented all the diffs of the JSON package on the list, but unfortunately, I uploaded the versions in the reverse order. :D)

Better luck next time ;-)
