### ISSUE TITLE
Debugger assumes size of its notifier if the notifier is closed directly via Proceed or Abandon

### ISSUE THREAD

**Issue by j4yk** [squeak-smalltalk/squeak-object-memory#58]
For a while, tool windows have been remembering the last size of one of their kind. This is also true for the debugger. The debugger comes in two display forms: the smaller notifier, which just shows a glimpse of the stack trace, a title, and the Proceed, Abandon, Debug buttons; and the full debugger with the additional stepping buttons, code pane, and inspectors.

The problem: after clicking Proceed or Abandon in the notifier, the full debugger remembers the size of the just closed notifier window, which is much too small for the full debugger. Subsequently, the debugger must be resized first for productive use.

![image](https://user-images.githubusercontent.com/151175/178153736-5e463338-9b85-4c71-81f6-7a253759586c.png)

Funnily enough, the full debugger does not seem to remember its size when you "Proceed" from within the full debugger... closing the debugger with the (x) window decoration does.

Expectation: the full debugger remembered size should be separate from the notifier remembered size. In any case, the buttons of the notifier should not overwrite the remembered size of the full debugger.

Squeak update 22050.
"Open tools attached to mouse cursor" enabled

**Comment by LinqLover** [comment]
Fix for this is prepared, should finally merge it during the next weeks 😅

**Comment by codeZeilen** [comment]
@LinqLover Was this merged?

**Comment by LinqLover** [comment]
> @LinqLover Was this merged?

@codeZeilen I think @marceltaeumel did this some time ago. Haven't checked yet ...

**Comment by marceltaeumel** [comment]
The preference `RealEstateAgent rememberWindowExtent` should have a better experience by now. Enable it and give it a try. That bug here should not happen anymore. That new behavior is part of Squeak 6.1alpha since January 2023. I will close this issue.
