### ISSUE TITLE
Squeak 6.0 alpha "Instances of UndefinedObject are not indexable" error under Windows 10 Chinese Edition

### ISSUE THREAD

**Issue by dram** [squeak-smalltalk/squeak-object-memory#6]
When launching Squeak 6.0 alpha under Windows 10 Chinese Edition, following error is occurred:

![image](https://user-images.githubusercontent.com/517130/164232430-fa18caf9-3586-4120-bc4b-585a7345e75e.png)

It seems that both `latin1Map` and `latin1Encodings` of `CNGBTextConverter` are `nil`.

Squeak version: Squeak6.0alpha-21599-64bit-202112201228-Windows-x64

**Comment by marceltaeumel** [comment]
Thank you for reporting this issue! Feel free to reach out if you are willing to contribute a Chinese translation for Squeak 6.0. 😄 

Fixed via Multilingual-mt.281. If you cannot update the image on your platform, please download a newer one:
http://files.squeak.org/trunk/Squeak6.0alpha-21638-64bit/Squeak6.0alpha-21638-64bit-202204190959-Windows-x64.zip

**Comment by dram** [comment]
Fix confirmed, thanks!

Regarding to translation, will have a try if I get time. 😀
