### ISSUE TITLE
Menu subitems are not accessable via mouse in some cases

### ISSUE THREAD

**Issue by vaidasd** [squeak-smalltalk/squeak-object-memory#61]
In Squeak 6.0 menu subitems are not accessable via mouse

https://user-images.githubusercontent.com/25151329/178519209-071f0a95-c672-4c44-8463-9ce4ee911ae4.mp4

**Comment by marceltaeumel** [comment]
I cannot reproduce that issue in Squeak 6.0. Please list the steps.

**Comment by vaidasd** [comment]
Correct. I used Squeak 6.0 alpha version updated up until the release. I wander where the difference came from. Sorry for noise.
