### ISSUE TITLE
Squeak 6.0 doesn't display Thai text.

### ISSUE THREAD

**Issue by veer66** [squeak-smalltalk/squeak-object-memory#64]
I try Squeak 6.0 on openSUSE Tumbleweed with KDE Plasma. I both typed directly to Squeak and pasted it from Emacs. Squeak only showed question marks.

![image](https://user-images.githubusercontent.com/370688/179331026-a64ce74c-c5a5-4a55-843c-2a34ca77b54f.png)

**Comment by marceltaeumel** [comment]
Install an appropriate font via "Apps > Font Importer". There is no elaborate font stack in Squeak but you could use that font as "Fallback Font" or just use it where you need it via the context menu "Set font..." or "Set style...".

![grafik](https://user-images.githubusercontent.com/5765308/183414093-a3d06190-9c11-4495-80a0-c2f22046438e.png)
