### ISSUE TITLE
Pharo 10:0 step over block while debugging causes Pharo Smalltalk system to hang

### ISSUE THREAD

**Issue by pjgoodall** [squeak-smalltalk/squeak-object-memory#76]
I reinstalled pharo-launcher yesterday, and downloaded a 10.0 image to run some scripts in. Playing with ChatGPT.
I did not load anything into the image, I had never saved the image. 
System hung twice debugging the same code in a Playground.

The state of the launcher:
![image](https://user-images.githubusercontent.com/719962/206355466-b0c454a8-4679-41e4-afff-ca934022e97e.png)

I have attached the PharoDebug.log - which seems to capture the action. If I can help by providing more information please let me know.

My platform:

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

kernel: 5.15.0-56-generic 
```

[PharoDebug.log](https://github.com/squeak-smalltalk/squeak-object-memory/files/10182057/PharoDebug.log)

**Comment by StephanEggermont** [comment]
Full screen is indeed a well-known separate issue

**Comment by LinqLover** [comment]
This issue tracker is about Squeak. I think you wanted to report your issue on https://github.com/pharo-project/pharo/issues instead. :-)

**Comment by pjgoodall** [comment]
Unable to reproduce when stepping through while creating a new issue. The log may be of interest to someone.

**Comment by pjgoodall** [comment]
Unable to reproduce when stepping through while creating a new issue. The log may be of interest to someone.
