### ISSUE TITLE
'preserver trash' prefference ceased to work

### ISSUE THREAD

**Issue by vaidasd** [squeak-smalltalk/squeak-object-memory#80]
It works for Squeak6.0 at update: #22104, but does not work update: #22122

**Comment by codeZeilen** [comment]
Some initial insight on this issue: The feature still works, but the deleted morphs are put on weird locations within the pages of the trash book.

**Comment by codeZeilen** [comment]
Fixed for 6.1 in MorphicExtras-pre.347 and MorphicExtrasTests-pre.8.

@marceltaeumel Do we want to consider this for backporting to 6.0?

**Comment by marceltaeumel** [comment]
Strange fix but I backported it. A call to `#position:` does never require an extra `#fullBounds` unless one immediatly requires updated, layout-specific geometry afterwards.

**Comment by codeZeilen** [comment]
> A call to #position: does never require an extra #fullBounds unless one immediatly requires updated, layout-specific geometry afterwards.

Which is exactly what is required here. The setting of position is only used to force a layout of the submorphs in the AlignmentMorph. Afterwards the submorphs are extracted from the AlignmentMorph again and added to the actual PageMorph. The AlignmentMorph is only temporary.
