### ISSUE TITLE
MessageTrace "implementors" on a missing method raises MessageNotUnderstood by UndefinedObject

### ISSUE THREAD

**Issue by j4yk** [squeak-smalltalk/squeak-object-memory#88]
In a MessageTrace, when a method gets removed by another tool while the trace is still open, and the method is selected again in the trace, it shows "Missing" in the source pane. That is all right. However the "implementors" action (via the button, pressing the shortcut in the list, or from the context menu of the list) raises a debugger with "MessageNotUnderstood: UndefinedObject>>messages". It should have added methods with the same selector instead, if any.

All the other buttons seem to work properly, or at least don't raise an error.

**Comment by LinqLover** [comment]
Fixed via Tools-ct.1228

**Comment by LinqLover** [comment]
Someone with the necessary permissions, please close this issue, sigh ... (Or would you give *me* the permission? :-))
